## About Embedding 关于词嵌入遇到的一些问题

最简单的随机数生成器

In [3]:
import numpy as np

a = np.random.default_rng(42)
print(a.random(5))


b = np.random.default_rng(42)
print(b.random(5))

c = np.random.default_rng(7)
print(c.random(5))

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.62509547 0.8972138  0.77568569 0.22520719 0.30016628]


id怎么来的 idx2word和word2idx是哪来的

In [10]:
from collections import Counter

toy = ['the', 'cat', 'sat', 'the', 'dog', 'sat', 'the', 'cat', 'ran', 'the', 'cat', 'zzz']
c = Counter(toy)
print("1. 词频：", c)

kept = [(w, n) for w, n in c.most_common() if n >= 2]
print("2. 保留：", kept)

idx2word = [w for w, _ in kept]
print("3. idx2word:", idx2word)

print(idx2word[0])   # the
print(idx2word[1])   # cat
print(idx2word[2])   # sat

word2idx = {w: i for i, w in enumerate(idx2word)}
print("4. word2idx:", word2idx)

1. 词频： Counter({'the': 4, 'cat': 3, 'sat': 2, 'dog': 1, 'ran': 1, 'zzz': 1})
2. 保留： [('the', 4), ('cat', 3), ('sat', 2)]
3. idx2word: ['the', 'cat', 'sat']
the
cat
sat
4. word2idx: {'the': 0, 'cat': 1, 'sat': 2}
