### 关于张量
张量表示一个数值组成的数组，这个数组可能有多个维度

In [3]:
import torch

x = torch.arange(12)
print(x)

y = x.reshape(3, 4)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


全零、全1、其他常量张量创建

In [4]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

多个张量连结